# Generated by Django 5.1.1 on 2024-11-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_employee_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
